apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: example-java-maven-yiwj
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a2e8a997d4cbe88f34daa7be5be6329863236432406208c061842a8d0733b775
        name: my-java-springboot
        resources: {}
status: {}
